(function initBattlePlanetClient(globalScope) {
const DEFAULT_SIZE={width:1024,height:700};
const RESIZE_THROTTLE_MS=100;
const CAMERA_LERP=0.12;
const CAMERA_SUN_WEIGHT=0.08;
const MIN_ZOOM=0.42;
const MAX_ZOOM=1.45;
const DEFAULT_ZOOM=0.52;
const ZOOM_STEP=0.08;
const INTERPOLATION_DELAY_MS=120;
const MAX_SNAPSHOT_BUFFER=90;
const UI_TEXT_REFRESH_MS=140;
const PERF_SAMPLE_WINDOW=90;
const DPR_CAP=1;
const TARGET_FRAME_MS=1000/60;
const VISIBILITY_MARGIN=96;
const hostElement=document.getElementById("gameRender");
const controlsElement=document.getElementById("gameControls");
const leaderboardElement=document.createElement("div");
leaderboardElement.className="leaderboardOverlay";
leaderboardElement.hidden=true;
hostElement.appendChild(leaderboardElement);
const canvas=document.createElement("canvas");
hostElement.appendChild(canvas);
const ctx=canvas.getContext("2d",{alpha:false,desynchronized:true});
const audioState={context:null,masterGain:null,playedExplosions:new Set()};
const cache={dpr:1,backgroundLayers:[],arena:null,sun:null,arenaKey:"",sunKey:"",backgroundKey:""};
const perfState={frameCount:0,lastUpdatedAt:0,sampleStartedAt:0,totals:{frame:0,background:0,arena:0,entities:0,effects:0,ui:0},snapshot:null};
let viewport={width:DEFAULT_SIZE.width,height:DEFAULT_SIZE.height,centerX:DEFAULT_SIZE.width/2,centerY:DEFAULT_SIZE.height/2};
let resizeTimestamp=0,zoom=DEFAULT_ZOOM,inputSender=()=>{},camera={x:0,y:0},pointerState={x:viewport.centerX,y:viewport.centerY,down:false},showLeaderboard=false,isRunning=false,animationFrame=null,snapshotBuffer=[],serverOffsetEstimate=null,lastUiTextUpdateAt=0,lastControlsText="",lastLeaderboardText="",lastRenderAt=0,networkState=emptyState(),hasInitialCamera=false,roundHistory=new Map(),resolvedRoundStatus=null;
buildBackgroundLayers();buildArena();buildSun();attachInputListeners();resizeBackingStore();render();
function emptyState(){return{status:"waiting",serverTime:0,tickNumber:0,worldRadius:1750,sun:{x:0,y:0,radius:110},players:[],enemies:[],rocks:[],explosions:[],playerId:undefined};}
function makeCanvas(w,h){const c=document.createElement("canvas");c.width=w;c.height=h;return c;}
function rgba(color,a){const r=(color>>16)&255,g=(color>>8)&255,b=color&255;return `rgba(${r}, ${g}, ${b}, ${a})`;}
function fillCircle(target,x,y,r,fill){target.beginPath();target.fillStyle=fill;target.arc(x,y,r,0,Math.PI*2);target.fill();}
function strokeCircle(target,x,y,r,stroke,w){target.beginPath();target.strokeStyle=stroke;target.lineWidth=w;target.arc(x,y,r,0,Math.PI*2);target.stroke();}
function randomFactory(seed){let state=seed;return()=>{state=(state*1664525+1013904223)%4294967296;return state/4294967296;};}
function buildBackgroundLayers(){const key=`${Math.round(viewport.width)}x${Math.round(viewport.height)}`;if(key===cache.backgroundKey&&cache.backgroundLayers.length===3)return;cache.backgroundKey=key;const width=Math.max(1,Math.round(viewport.width)),height=Math.max(1,Math.round(viewport.height)),layerConfigs=[{seed:42,count:110,minRadius:0.8,maxRadius:1.8,alphaMin:0.14,alphaMax:0.28,color:"255,255,255"},{seed:84,count:75,minRadius:1.2,maxRadius:2.4,alphaMin:0.12,alphaMax:0.24,color:"122,205,255"},{seed:126,count:34,minRadius:1.8,maxRadius:3.6,alphaMin:0.08,alphaMax:0.18,color:"255,212,140"}];cache.backgroundLayers=layerConfigs.map((config)=>{const node=makeCanvas(width,height),g=node.getContext("2d"),random=randomFactory(config.seed);for(let i=0;i<config.count;i+=1){fillCircle(g,random()*width,random()*height,config.minRadius+random()*(config.maxRadius-config.minRadius),`rgba(${config.color},${config.alphaMin+random()*(config.alphaMax-config.alphaMin)})`);}return node;});}
function buildArena(){const key=`${Math.round(networkState.worldRadius)}`;if(key===cache.arenaKey&&cache.arena)return;cache.arenaKey=key;const radius=Math.ceil(networkState.worldRadius+18),node=makeCanvas(radius*2,radius*2),g=node.getContext("2d");g.translate(radius,radius);strokeCircle(g,0,0,networkState.worldRadius,"#0d2335",10);strokeCircle(g,0,0,networkState.worldRadius,"rgba(96,212,255,0.32)",4);strokeCircle(g,0,0,networkState.worldRadius*0.82,"rgba(255,179,71,0.3)",1.5);cache.arena=node;}
function buildSun(){const key=`${Math.round(networkState.sun.radius)}`;if(key===cache.sunKey&&cache.sun)return;cache.sunKey=key;const extent=Math.ceil(networkState.sun.radius+54),node=makeCanvas(extent*2,extent*2),g=node.getContext("2d");g.translate(extent,extent);fillCircle(g,0,0,networkState.sun.radius+42,"rgba(255,179,71,0.08)");fillCircle(g,0,0,networkState.sun.radius+22,"rgba(255,217,122,0.12)");fillCircle(g,0,0,networkState.sun.radius,"rgba(255,200,87,0.92)");fillCircle(g,-networkState.sun.radius*0.22,-networkState.sun.radius*0.24,networkState.sun.radius*0.52,"rgba(255,255,255,0.18)");strokeCircle(g,0,0,networkState.sun.radius+10,"rgba(255,226,154,0.12)",8);cache.sun=node;}
function resizeBackingStore(){const inner=getHostInnerSize(),dpr=Math.min(window.devicePixelRatio||1,DPR_CAP),nextWidth=Math.max(1,Math.round(inner.width)),nextHeight=Math.max(1,Math.round(inner.height));viewport={width:nextWidth,height:nextHeight,centerX:nextWidth/2,centerY:nextHeight/2};pointerState.x=Math.min(nextWidth,Math.max(0,pointerState.x));pointerState.y=Math.min(nextHeight,Math.max(0,pointerState.y));if(dpr===cache.dpr&&canvas.width===Math.round(nextWidth*dpr)&&canvas.height===Math.round(nextHeight*dpr))return;cache.dpr=dpr;canvas.width=Math.round(nextWidth*dpr);canvas.height=Math.round(nextHeight*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;}
function getHostInnerSize(){const styles=window.getComputedStyle(hostElement),paddingX=parseFloat(styles.paddingLeft||"0")+parseFloat(styles.paddingRight||"0"),paddingY=parseFloat(styles.paddingTop||"0")+parseFloat(styles.paddingBottom||"0");return{width:Math.max(1,Math.floor(hostElement.clientWidth-paddingX)),height:Math.max(1,Math.floor(hostElement.clientHeight-paddingY))};}
function attachInputListeners(){function updatePointer(event){const rect=canvas.getBoundingClientRect();pointerState.x=((event.clientX-rect.left)/Math.max(rect.width,1))*viewport.width;pointerState.y=((event.clientY-rect.top)/Math.max(rect.height,1))*viewport.height;}canvas.addEventListener("mousemove",(event)=>{updatePointer(event);if(!battlePlanetGame.isActive()||!getPlayer())return;const worldPoint=screenToWorld(pointerState.x,pointerState.y);inputSender({x:worldPoint.x,y:worldPoint.y,fireHeld:pointerState.down});});canvas.addEventListener("mousedown",(event)=>{updatePointer(event);if(!battlePlanetGame.isActive()||!getPlayer())return;pointerState.down=true;ensureAudio();playShootSound();const worldPoint=screenToWorld(pointerState.x,pointerState.y);inputSender({x:worldPoint.x,y:worldPoint.y,fireHeld:true,firePulse:true});});window.addEventListener("mouseup",()=>{if(!pointerState.down)return;pointerState.down=false;if(!battlePlanetGame.isActive()||!getPlayer())return;const worldPoint=screenToWorld(pointerState.x,pointerState.y);inputSender({x:worldPoint.x,y:worldPoint.y,fireHeld:false});});canvas.addEventListener("wheel",(event)=>{event.preventDefault();zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,zoom-Math.sign(event.deltaY)*ZOOM_STEP));},{passive:false});canvas.addEventListener("contextmenu",(event)=>event.preventDefault());window.addEventListener("resize",()=>battlePlanetGame.resizeToContainer());window.addEventListener("keydown",(event)=>{if(event.key==="Tab"&&battlePlanetGame.isActive()){event.preventDefault();showLeaderboard=true;}});window.addEventListener("keyup",(event)=>{if(event.key==="Tab")showLeaderboard=false;});}
function ensureAudio(){if(audioState.context){if(audioState.context.state==="suspended")audioState.context.resume();return audioState.context;}const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)return null;const audioContext=new AudioContextClass(),masterGain=audioContext.createGain();masterGain.gain.value=0.06;masterGain.connect(audioContext.destination);audioState.context=audioContext;audioState.masterGain=masterGain;return audioContext;}
function tone({frequency,endFrequency,duration,type,volume}){const audioContext=ensureAudio();if(!audioContext||!audioState.masterGain)return;const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,audioContext.currentTime);if(typeof endFrequency==="number")oscillator.frequency.exponentialRampToValueAtTime(endFrequency,audioContext.currentTime+duration);gain.gain.setValueAtTime(volume,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(0.0001,audioContext.currentTime+duration);oscillator.connect(gain);gain.connect(audioState.masterGain);oscillator.start();oscillator.stop(audioContext.currentTime+duration);}
function playShootSound(){tone({frequency:240,endFrequency:120,duration:0.08,type:"triangle",volume:0.3});}
function playExplosionSound(scale){tone({frequency:180*scale,endFrequency:48,duration:0.18,type:"sawtooth",volume:0.24});tone({frequency:90*scale,endFrequency:36,duration:0.24,type:"triangle",volume:0.16});}
function lerp(start,end,alpha){return start+(end-start)*alpha;}
function normalizeAngle(angle){let value=angle;while(value<=-Math.PI)value+=Math.PI*2;while(value>Math.PI)value-=Math.PI*2;return value;}
function lerpAngle(start,end,alpha){return normalizeAngle(start+normalizeAngle(end-start)*alpha);}
function cloneState(state){return{...state,sun:{...state.sun},players:state.players.map((entry)=>({...entry})),enemies:state.enemies.map((entry)=>({...entry})),rocks:state.rocks.map((entry)=>({...entry})),explosions:(state.explosions||[]).map((entry)=>({...entry}))};}
function interpolateEntity(previous,next,alpha){const base=next||previous;if(!previous||!next)return{...base};return{...base,x:lerp(previous.x,next.x,alpha),y:lerp(previous.y,next.y,alpha),vx:typeof previous.vx==="number"&&typeof next.vx==="number"?lerp(previous.vx,next.vx,alpha):base.vx,vy:typeof previous.vy==="number"&&typeof next.vy==="number"?lerp(previous.vy,next.vy,alpha):base.vy,radius:typeof previous.radius==="number"&&typeof next.radius==="number"?lerp(previous.radius,next.radius,alpha):base.radius,angle:typeof previous.angle==="number"&&typeof next.angle==="number"?lerpAngle(previous.angle,next.angle,alpha):base.angle,modifier:typeof previous.modifier==="number"&&typeof next.modifier==="number"?lerp(previous.modifier,next.modifier,alpha):base.modifier};}
function interpolateList(previousList,nextList,alpha){const previousMap=new Map(previousList.map((entry)=>[entry.id,entry])),nextMap=new Map(nextList.map((entry)=>[entry.id,entry])),ids=new Set([...previousMap.keys(),...nextMap.keys()]),result=[];for(const id of ids)result.push(interpolateEntity(previousMap.get(id),nextMap.get(id),alpha));return result;}
function interpolatedState(){if(snapshotBuffer.length===0)return networkState;if(snapshotBuffer.length===1||serverOffsetEstimate===null)return cloneState(snapshotBuffer[snapshotBuffer.length-1]);const renderServerTime=Date.now()-serverOffsetEstimate-INTERPOLATION_DELAY_MS;let previous=snapshotBuffer[0],next=snapshotBuffer[snapshotBuffer.length-1];for(let i=0;i<snapshotBuffer.length;i+=1){const snapshot=snapshotBuffer[i];if(snapshot.serverTime<=renderServerTime)previous=snapshot;if(snapshot.serverTime>=renderServerTime){next=snapshot;break;}}if(previous===next)return cloneState(previous);const duration=Math.max(1,next.serverTime-previous.serverTime),alpha=Math.max(0,Math.min(1,(renderServerTime-previous.serverTime)/duration));return{serverTime:lerp(previous.serverTime,next.serverTime,alpha),tickNumber:alpha<0.5?previous.tickNumber:next.tickNumber,status:alpha<0.5?previous.status:next.status,worldRadius:lerp(previous.worldRadius,next.worldRadius,alpha),sun:interpolateEntity(previous.sun,next.sun,alpha),players:interpolateList(previous.players,next.players,alpha),enemies:interpolateList(previous.enemies,next.enemies,alpha),rocks:interpolateList(previous.rocks,next.rocks,alpha),explosions:interpolateList(previous.explosions||[],next.explosions||[],alpha),playerId:next.playerId||previous.playerId};}
function screenToWorld(screenX,screenY){return{x:(screenX-viewport.centerX)/zoom+camera.x,y:(screenY-viewport.centerY)/zoom+camera.y};}
function worldToScreenX(worldX){return(worldX-camera.x)*zoom+viewport.centerX;}
function worldToScreenY(worldY){return(worldY-camera.y)*zoom+viewport.centerY;}
function worldToScreenSize(size){return size*zoom;}
function isCircleVisible(x,y,radius){return x+radius>=-VISIBILITY_MARGIN&&x-radius<=viewport.width+VISIBILITY_MARGIN&&y+radius>=-VISIBILITY_MARGIN&&y-radius<=viewport.height+VISIBILITY_MARGIN;}
function perfNow(){return performance.now();}
function roundPerfValue(value){return Math.round(value*100)/100;}
function recordPerfSample(sample){const now=Date.now();if(perfState.frameCount===0)perfState.sampleStartedAt=now;perfState.frameCount+=1;perfState.totals.frame+=sample.frame;perfState.totals.background+=sample.background;perfState.totals.arena+=sample.arena;perfState.totals.entities+=sample.entities;perfState.totals.effects+=sample.effects;perfState.totals.ui+=sample.ui;if(perfState.frameCount<PERF_SAMPLE_WINDOW)return;const elapsedMs=Math.max(1,now-perfState.sampleStartedAt);perfState.snapshot={fps:roundPerfValue((perfState.frameCount*1000)/elapsedMs),frameMs:roundPerfValue(perfState.totals.frame/perfState.frameCount),backgroundMs:roundPerfValue(perfState.totals.background/perfState.frameCount),arenaMs:roundPerfValue(perfState.totals.arena/perfState.frameCount),entitiesMs:roundPerfValue(perfState.totals.entities/perfState.frameCount),effectsMs:roundPerfValue(perfState.totals.effects/perfState.frameCount),uiMs:roundPerfValue(perfState.totals.ui/perfState.frameCount),sampleMs:elapsedMs,frames:perfState.frameCount,viewport:{width:viewport.width,height:viewport.height},zoom:roundPerfValue(zoom),updatedAt:now};perfState.frameCount=0;perfState.sampleStartedAt=0;perfState.totals={frame:0,background:0,arena:0,entities:0,effects:0,ui:0};perfState.lastUpdatedAt=now;globalScope.BattlePlanetPerf=perfState.snapshot;}
function getPerfStats(){return perfState.snapshot||{fps:0,frameMs:0,backgroundMs:0,arenaMs:0,entitiesMs:0,effectsMs:0,uiMs:0,sampleMs:0,frames:0,viewport:{width:viewport.width,height:viewport.height},zoom:roundPerfValue(zoom),updatedAt:perfState.lastUpdatedAt};}
function historyForEntity(entity){const existing=roundHistory.get(entity.id);if(existing){existing.name=entity.name||existing.name;existing.team=entity.team||existing.team;return existing;}const created={id:entity.id,name:entity.name||entity.id,team:entity.team||"unknown",rounds:0,wins:0,losses:0,deaths:0,lastOutcome:""};roundHistory.set(entity.id,created);return created;}
function updateRoundHistory(state){const currentEntities=[...state.players,...state.enemies];currentEntities.forEach((entity)=>historyForEntity(entity));if(state.status==="playing"){resolvedRoundStatus=null;return;}if(resolvedRoundStatus===state.status)return;resolvedRoundStatus=state.status;const playerTeamWon=state.status==="won";for(const entity of currentEntities){const history=historyForEntity(entity),alive=entity.alive!==false,isPlayerTeam=entity.team!=="enemy";history.rounds+=1;if((playerTeamWon&&isPlayerTeam)||(!playerTeamWon&&!isPlayerTeam))history.wins+=1;else history.losses+=1;if(!alive)history.deaths+=1;history.lastOutcome=alive?"survived":"destroyed";}}
function leaderboardLine(entry,{alive,instability,isLocalPlayer,history}){const marker=isLocalPlayer?">":" ";const stateLabel=alive?"alive":"dead";return `${marker} ${entry.name}  ${stateLabel}  +${instability}%  W${history.wins}-L${history.losses}  D${history.deaths}`;}
function distanceBetween(a,b){const dx=a.x-b.x,dy=a.y-b.y;return Math.sqrt(dx*dx+dy*dy);}
function getPlayer(){return networkState.players.find((player)=>player.id===networkState.playerId);}
function updateCamera(){const player=getPlayer();if(!player)return;const targetX=player.x*(1-CAMERA_SUN_WEIGHT)+networkState.sun.x*CAMERA_SUN_WEIGHT,targetY=player.y*(1-CAMERA_SUN_WEIGHT)+networkState.sun.y*CAMERA_SUN_WEIGHT;camera.x+=((targetX-camera.x)*CAMERA_LERP);camera.y+=((targetY-camera.y)*CAMERA_LERP);}
function updateUi(){const aliveEnemies=networkState.enemies.filter((enemy)=>enemy.alive!==false).length,controlsText=networkState.status==="won"?"Round cleared. Restarting automatically. Hold Tab for leaderboard.":networkState.status==="lost"?"All players are down. Restarting automatically. Hold Tab for leaderboard.":`Aim with the cursor, click to eject a rock, wheel to zoom, hold Tab for leaderboard. Enemies left: ${aliveEnemies}.`,now=Date.now(),shouldRefresh=now-lastUiTextUpdateAt>=UI_TEXT_REFRESH_MS;if(shouldRefresh&&controlsText!==lastControlsText){controlsElement.textContent=controlsText;lastControlsText=controlsText;}leaderboardElement.hidden=!showLeaderboard;if(showLeaderboard){const perf=getPerfStats(),sortEntities=(left,right)=>{const aliveDelta=(right.alive!==false)-(left.alive!==false);if(aliveDelta!==0)return aliveDelta;return (right.modifier||1)-(left.modifier||1);},players=[...networkState.players].sort(sortEntities).map((entry)=>{const history=historyForEntity(entry);return leaderboardLine(entry,{alive:entry.alive!==false,instability:Math.round(((entry.modifier||1)-1)*100),isLocalPlayer:entry.id===networkState.playerId,history});}),bots=[...networkState.enemies].sort(sortEntities).map((entry)=>{const history=historyForEntity(entry);return leaderboardLine(entry,{alive:entry.alive!==false,instability:Math.round(((entry.modifier||1)-1)*100),isLocalPlayer:false,history});}),historySummary=[...roundHistory.values()].sort((left,right)=>{if(right.wins!==left.wins)return right.wins-left.wins;if(left.losses!==right.losses)return left.losses-right.losses;return left.name.localeCompare(right.name);}).slice(0,8).map((entry)=>`${entry.name}  W${entry.wins}-L${entry.losses}  D${entry.deaths}`),leaderboardText=["Match Board",`Status: ${networkState.status}   Enemies left: ${aliveEnemies}`,"","Pilots",...(players.length>0?players:["No pilots connected"]),"","Bots",...(bots.length>0?bots:["No bots"]),"","Campaign",...(historySummary.length>0?historySummary:["No completed rounds yet"]),"","Rendering",`FPS ${perf.fps}   ${perf.frames} frames / ${perf.sampleMs}ms`,`Cost ${perf.frameMs}ms   BG ${perf.backgroundMs}   Arena ${perf.arenaMs}`,`Entities ${perf.entitiesMs}   Effects ${perf.effectsMs}   UI ${perf.uiMs}`,`Viewport ${perf.viewport.width}x${perf.viewport.height}  Zoom ${perf.zoom}`].join("\n");if(shouldRefresh&&leaderboardText!==lastLeaderboardText){leaderboardElement.textContent=leaderboardText;lastLeaderboardText=leaderboardText;}}else if(lastLeaderboardText){lastLeaderboardText="";}if(shouldRefresh)lastUiTextUpdateAt=now;}
function updateAudio(){const explosions=networkState.explosions||[],recentIds=new Set();for(const explosion of explosions){recentIds.add(explosion.id);if(!audioState.playedExplosions.has(explosion.id)){ensureAudio();playExplosionSound(Math.max(0.8,Math.min(1.6,explosion.radius/18)));audioState.playedExplosions.add(explosion.id);}}audioState.playedExplosions.forEach((id)=>{if(!recentIds.has(id))audioState.playedExplosions.delete(id);});}
function labelForPlanet(planet,isLocalPlayer){const instabilityPercent=Math.round(((planet.modifier||1)-1)*100),fallbackName=isLocalPlayer?"You":(planet.team==="enemy"?"Bot":"Player");return `${planet.name||fallbackName}  +${instabilityPercent}%`;}
function drawLabel(text,x,y,fillStyle,fontSize){ctx.font=`700 ${fontSize}px 'Trebuchet MS', 'Segoe UI', sans-serif`;ctx.textAlign="center";ctx.textBaseline="bottom";ctx.lineJoin="round";ctx.strokeStyle="#07111d";ctx.lineWidth=Math.max(3,fontSize*0.34);ctx.strokeText(text,x,y);ctx.fillStyle=fillStyle;ctx.fillText(text,x,y);}
function renderPlanet(planet,isLocalPlayer){const x=worldToScreenX(planet.x),y=worldToScreenY(planet.y),screenRadius=Math.max(2,worldToScreenSize(planet.radius)),alpha=planet.alive===false?0.35:0.95,instability=Math.max(0,Math.min(1,((planet.modifier||1)-1)/5)),auraRadius=Math.max(screenRadius+2,worldToScreenSize(planet.radius+12+instability*12));if(!isCircleVisible(x,y,auraRadius))return;fillCircle(ctx,x,y,auraRadius,rgba(planet.color,isLocalPlayer?0.18+instability*0.08:0.1+instability*0.06));fillCircle(ctx,x-screenRadius*0.22,y-screenRadius*0.24,screenRadius*0.78,`rgba(255,255,255,${alpha*0.14})`);fillCircle(ctx,x,y,screenRadius,rgba(planet.color,alpha));strokeCircle(ctx,x,y,screenRadius+Math.max(2,worldToScreenSize(4+instability*2)),isLocalPlayer?"rgba(255,255,255,0.30)":"rgba(228,237,247,0.24)",Math.max(1.25,isLocalPlayer?worldToScreenSize(3):worldToScreenSize(2)));strokeCircle(ctx,x,y,Math.max(5,screenRadius*0.55),"rgba(255,255,255,0.18)",Math.max(1,worldToScreenSize(1.5)));const noseX=x+Math.cos(planet.angle)*(screenRadius+worldToScreenSize(8)),noseY=y+Math.sin(planet.angle)*(screenRadius+worldToScreenSize(8)),leftX=x+Math.cos(planet.angle+2.4)*Math.max(2,screenRadius-worldToScreenSize(4)),leftY=y+Math.sin(planet.angle+2.4)*Math.max(2,screenRadius-worldToScreenSize(4)),rightX=x+Math.cos(planet.angle-2.4)*Math.max(2,screenRadius-worldToScreenSize(4)),rightY=y+Math.sin(planet.angle-2.4)*Math.max(2,screenRadius-worldToScreenSize(4));ctx.strokeStyle=isLocalPlayer?"#ffffff":"#c9d6e2";ctx.lineWidth=Math.max(1.25,isLocalPlayer?worldToScreenSize(3):worldToScreenSize(2));ctx.beginPath();ctx.moveTo(noseX,noseY);ctx.lineTo(leftX,leftY);ctx.lineTo(rightX,rightY);ctx.closePath();ctx.stroke();const labelY=y-screenRadius-Math.max(10,worldToScreenSize(12));if(labelY>-VISIBILITY_MARGIN&&labelY<viewport.height+VISIBILITY_MARGIN){drawLabel(labelForPlanet(planet,isLocalPlayer),x,labelY,isLocalPlayer?"#ffffff":(planet.team==="enemy"?"#ffd7bf":"#d7e6f6"),Math.max(11,Math.min(18,12+zoom*3.5)));}}
function drawBackground(){const layers=cache.backgroundLayers;if(layers.length===0)return;ctx.fillStyle="#06111d";ctx.fillRect(0,0,viewport.width,viewport.height);const parallaxDepths=[0.08,0.16,0.28];for(let index=0;index<layers.length;index+=1){const layer=layers[index],depth=parallaxDepths[index]||0.1,offsetX=(-camera.x*depth)%viewport.width,offsetY=(-camera.y*depth)%viewport.height,startX=offsetX>0?offsetX-viewport.width:offsetX,startY=offsetY>0?offsetY-viewport.height:offsetY;for(let tileX=startX;tileX<viewport.width;tileX+=viewport.width){for(let tileY=startY;tileY<viewport.height;tileY+=viewport.height){ctx.drawImage(layer,tileX,tileY,viewport.width,viewport.height);}}}}
function renderGuides(){const player=getPlayer();if(!player)return;ctx.strokeStyle="rgba(255,209,102,0.28)";ctx.lineWidth=Math.max(1,worldToScreenSize(1.5));ctx.beginPath();ctx.moveTo(worldToScreenX(player.x),worldToScreenY(player.y));ctx.lineTo(worldToScreenX(networkState.sun.x),worldToScreenY(networkState.sun.y));ctx.stroke();if(player.alive!==false&&networkState.status==="playing"){ctx.strokeStyle="rgba(140,240,255,0.45)";ctx.beginPath();ctx.moveTo(worldToScreenX(player.x),worldToScreenY(player.y));ctx.lineTo(pointerState.x,pointerState.y);ctx.stroke();strokeCircle(ctx,pointerState.x,pointerState.y,8,"rgba(140,240,255,0.45)",1.5);}const playerDistance=distanceBetween(player,networkState.sun);if(playerDistance>networkState.worldRadius*0.82){const intensity=Math.min(1,(playerDistance-networkState.worldRadius*0.82)/(networkState.worldRadius*0.18));ctx.strokeStyle=`rgba(255,107,107,${0.18+intensity*0.26})`;ctx.lineWidth=14;ctx.strokeRect(7,7,viewport.width-14,viewport.height-14);}}
function render(){buildBackgroundLayers();const frameStart=perfNow();ctx.clearRect(0,0,viewport.width,viewport.height);const backgroundStart=perfNow();drawBackground();const backgroundEnd=perfNow();buildArena();buildSun();const arenaDrawStart=perfNow(),arenaSize=cache.arena.width*zoom,arenaX=worldToScreenX(networkState.sun.x)-arenaSize/2,arenaY=worldToScreenY(networkState.sun.y)-arenaSize/2;ctx.drawImage(cache.arena,arenaX,arenaY,arenaSize,arenaSize);const sunSize=cache.sun.width*zoom,sunX=worldToScreenX(networkState.sun.x)-sunSize/2,sunY=worldToScreenY(networkState.sun.y)-sunSize/2;ctx.drawImage(cache.sun,sunX,sunY,sunSize,sunSize);const arenaDrawEnd=perfNow();const entitiesStart=perfNow();for(const rock of networkState.rocks){const x=worldToScreenX(rock.x),y=worldToScreenY(rock.y),screenRadius=Math.max(1.5,worldToScreenSize(rock.radius));if(!isCircleVisible(x,y,screenRadius+8))continue;fillCircle(ctx,x,y,screenRadius+4,rgba(rock.color,0.18));fillCircle(ctx,x-1.2,y-1.2,Math.max(1.2,screenRadius*0.55),"rgba(255,255,255,0.14)");fillCircle(ctx,x,y,screenRadius,rgba(rock.color,0.95));}for(const player of networkState.players)renderPlanet(player,player.id===networkState.playerId);for(const enemy of networkState.enemies)renderPlanet(enemy,false);const entitiesEnd=perfNow();const effectsStart=perfNow();for(const explosion of networkState.explosions||[]){const alpha=explosion.maxTtl?Math.max(0,explosion.ttl/explosion.maxTtl):0.5,radius=worldToScreenSize(explosion.radius*(1.35-alpha*0.35)),x=worldToScreenX(explosion.x),y=worldToScreenY(explosion.y);if(!isCircleVisible(x,y,radius+8))continue;strokeCircle(ctx,x,y,radius,rgba(explosion.color,alpha*0.9),Math.max(1.5,worldToScreenSize(3)));fillCircle(ctx,x,y,radius,rgba(explosion.color,alpha*0.18));}renderGuides();const effectsEnd=perfNow();const uiStart=perfNow();updateUi();const uiEnd=perfNow();recordPerfSample({frame:uiEnd-frameStart,background:backgroundEnd-backgroundStart,arena:arenaDrawEnd-arenaDrawStart,entities:entitiesEnd-entitiesStart,effects:effectsEnd-effectsStart,ui:uiEnd-uiStart});}
function frame(now){if(now-lastRenderAt<TARGET_FRAME_MS){if(isRunning)animationFrame=window.requestAnimationFrame(frame);return;}lastRenderAt=now;networkState=interpolatedState();updateCamera();updateAudio();render();if(isRunning)animationFrame=window.requestAnimationFrame(frame);}
const battlePlanetGame={start(){if(isRunning)return;isRunning=true;lastRenderAt=0;animationFrame=window.requestAnimationFrame(frame);},stop(){isRunning=false;if(animationFrame!==null){window.cancelAnimationFrame(animationFrame);animationFrame=null;}},resizeToContainer(){if(Date.now()-resizeTimestamp<RESIZE_THROTTLE_MS)return;resizeTimestamp=Date.now();resizeBackingStore();buildBackgroundLayers();canvas.style.display="block";canvas.style.width=`${viewport.width}px`;canvas.style.height=`${viewport.height}px`;render();},setInputSender(sender){inputSender=sender;},setState(nextState){const snapshot=cloneState(nextState),offsetSample=Date.now()-snapshot.serverTime;if(serverOffsetEstimate===null)serverOffsetEstimate=offsetSample;else{serverOffsetEstimate=Math.min(serverOffsetEstimate,offsetSample);serverOffsetEstimate=lerp(serverOffsetEstimate,offsetSample,0.02);}const existingIndex=snapshotBuffer.findIndex((entry)=>entry.tickNumber===snapshot.tickNumber);if(existingIndex>=0)snapshotBuffer[existingIndex]=snapshot;else snapshotBuffer.push(snapshot);snapshotBuffer.sort((left,right)=>left.serverTime-right.serverTime);if(snapshotBuffer.length>MAX_SNAPSHOT_BUFFER)snapshotBuffer=snapshotBuffer.slice(snapshotBuffer.length-MAX_SNAPSHOT_BUFFER);networkState=interpolatedState();updateRoundHistory(networkState);buildArena();buildSun();const player=getPlayer();if(player&&!hasInitialCamera){camera.x=player.x*(1-CAMERA_SUN_WEIGHT)+networkState.sun.x*CAMERA_SUN_WEIGHT;camera.y=player.y*(1-CAMERA_SUN_WEIGHT)+networkState.sun.y*CAMERA_SUN_WEIGHT;hasInitialCamera=true;}render();},clearState(){snapshotBuffer=[];serverOffsetEstimate=null;networkState=emptyState();audioState.playedExplosions.clear();lastUiTextUpdateAt=0;lastControlsText="";lastLeaderboardText="";lastRenderAt=0;camera={x:0,y:0};hasInitialCamera=false;showLeaderboard=false;resolvedRoundStatus=null;roundHistory=new Map();leaderboardElement.hidden=true;buildBackgroundLayers();buildArena();buildSun();render();},getPerfStats(){return getPerfStats();},isActive(){return isRunning&&hostElement.style.display!=="none";}};
battlePlanetGame.resizeToContainer();
globalScope.BattlePlanetGame=battlePlanetGame;
})(window);
